apiVersion: v1
kind: Secret
metadata:
  name: restapi-feed-secret
stringData:
  POSTGRES_USERNAME: ${POSTGRES_USERNAME}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_HOST: ${POSTGRES_HOST}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  JWT_SECRET: ${JWT_SECRET}
